In [45]:
import pandas as pd
import numpy as np
from plotnine import*
import calendar

In [46]:
df_airquality = pd.read_csv('Air_quality_analytics.csv')

In [47]:
# Converting date column as a date format

df_airquality['date'] = pd.to_datetime(df_airquality['date'], format = "%Y-%m-%d")
df_airquality.info()
df_airquality.head()

<class 'pandas.DataFrame'>
RangeIndex: 87084 entries, 0 to 87083
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              87084 non-null  int64
 1   date             87084 non-null  datetime64[us]
 2   site             87084 non-null  str
 3   parameter        87084 non-null  str
 4   index_value      87084 non-null  int64
 5   description      87084 non-null  str
 6   health_advisory  7573 non-null   str
 7   health_effects   7573 non-null   str
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 5.3 MB

,_id,date,site,parameter,index_value,description,health_advisory,health_effects
0,1,2016-01-01,Lawrenceville,PM25B,25,Good,NaN,NaN
1,2,2016-01-01,Flag Plaza,CO,0,Good,NaN,NaN
2,3,2016-01-01,Harrison Township,OZONE,31,Good,NaN,NaN
3,4,2016-01-01,Avalon,SO2,10,Good,NaN,NaN
4,5,2016-01-01,Lincoln,PM25,35,Good,NaN,NaN

In [48]:
df_airquality['parameter'].unique()

<StringArray>
[   'PM25B',       'CO',    'OZONE',      'SO2',     'PM25',     'PM10',
    'PM10B',  'PM25(2)',      'NO2',    'PM25T', 'PM25_640', 'PM10_640',
  'NO2_500',  'NO2_200',  'SO2_100',   'CO_PPB',  'SO2_PPM',   'CO_PPM',
  'SO2_PPB']
Length: 19, dtype: str

NOTE: The "Check" function is used to check is any problems are found within your dataframe

In [49]:
n_rows = len(df_airquality)
n_unique = df_airquality[['site', 'parameter', 'date']].drop_duplicates().shape[0]

print(n_rows, n_unique)
print(n_rows == n_unique)

# No Duplicates Confirmed

87084 87084
True

In [50]:
# Deleting partial year 2026

df_airquality = df_airquality[df_airquality['date'].dt.year != 2026]

In [51]:
# Adding month & month name column

df_airquality['month'] = df_airquality['date'].dt.month
df_airquality['month_name'] = df_airquality['month'].apply(lambda x: calendar.month_name[x])

In [52]:
# Adding Season Column

season = {1: 'Winter', 2: 'Winter', 3: 'Spring', 4: 'Spring', 5: 'Spring', 6: 'Summer', 7: 'Summer', 8: 'Summer', 9: 'Fall', 10: 'Fall', 11: 'Fall', 12: 'Winter'}
df_airquality['season'] = df_airquality['month'].map(season)

In [ ]:
#TO DO:

# Group by Pollutant and Season and take the Mean

In [54]:
# Reference

df_airquality.head()

,_id,date,site,parameter,index_value,description,health_advisory,health_effects,month,month_name,season
0,1,2016-01-01,Lawrenceville,PM25B,25,Good,NaN,NaN,1,January,Winter
1,2,2016-01-01,Flag Plaza,CO,0,Good,NaN,NaN,1,January,Winter
2,3,2016-01-01,Harrison Township,OZONE,31,Good,NaN,NaN,1,January,Winter
3,4,2016-01-01,Avalon,SO2,10,Good,NaN,NaN,1,January,Winter
4,5,2016-01-01,Lincoln,PM25,35,Good,NaN,NaN,1,January,Winter